apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: metrics-db
spec:
  version: 8.6.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: default
    count: 1
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            resources:
              requests:
                cpu: 1
                memory: 4G
              limits:
                cpu: 1
                memory: 4G
    config:
      node.store.allow_mmap: false
      xpack.security.authc:
        anonymous:
          username: anonymous_user
          roles: superuser, kibana_admin
          authz_exception: true
