apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: metrics-ui
spec:
  version: 8.6.2
  count: 1
  config:
    uiSettings:
      overrides:
        "theme:darkMode": true
    xpack.security.authc.providers:
      basic.basic1:
        order: 0
      anonymous.anonymous1:
        order: 1
        credentials:
          username: "anonymous_user"
          password: ""
  elasticsearchRef:
    name: metrics-db