apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: grafanadatasource-elasticsearch
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://metrics-db-es-http:9200
    isDefault: true
    database: "k6-metrics"
    basicAuth: true
    basicAuthUser: "elastic"
    jsonData:
      'tlsSkipVerify': true
      'timeInterval': "5s"
      'xpack': true
      'esVersion': "8.0.0"
      'timeField': "Time"
    secureJsonData:
      'basicAuthPassword': "secret"
    editable: true