{
 "title": "K6 Dashboard by Deepshore",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "scenario",
    "label": "Scenario",
    "query": "{\"find\": \"terms\", \"field\": \"MetricTags.scenario\", \"query\": \"*:*\"}"
   },
   {
    "name": "jobname",
    "query": "{\"find\": \"terms\", \"field\": \"MetricTags.job_name\", \"query\": \"*:*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of VUs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "MetricTags.instance_id",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "10"
       },
       "type": "terms"
      },
      { "field": "Time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Value", "id": "1", "settings": { "missing": "0" }, "type": "avg" }
     ],
     "query": "MetricName:vus && MetricTags.job_name:$jobname*\n",
     "timeField": "Time"
    }
   ]
  },
  {
   "title": "Number of HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "MetricName",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Value", "id": "1", "type": "sum" }
     ],
     "query": "MetricName:http_reqs && MetricTags.job_name:$jobname*\n",
     "timeField": "Time"
    }
   ]
  },
  {
   "title": "Raw Data",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "MetricTags.job_name:$jobname*\n",
     "timeField": "Time"
    }
   ]
  }
 ]
}